# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: ubuntu:16.04

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
before_script:
  - apt update
  - apt install npm -y
  - apt install python3 -y
  - pip install nodeenv
  - npm install electron-packager
  - npm install electron-installer-dmg

buildDMG:
  script:
   - npm install
   - electron-packager . CTVisualizer --platform=darwin --arch=x64 --out=./packaged-app
   - electron-installer-dmg ./packaged-app/CTVisualizer-darwin-x64/CTVisualizer.app CTVisualizer --out=./dmg
  artifacts:
    paths:
      - dmg/CTVisualizer.dmg

