# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
before_script:
    - whoami
#   - apt update
#   - apt install curl -y
#   - curl -sL https://deb.nodesource.com/setup_10.x | bash -
#   - apt install nodejs -y
#   - apt install npm -y
# #   - apt install python-pip -y
# #   - pip install virtualenv
# #   - virtualenv venv
# #   - source venv/bin/activate
# #   - pip install nodeenv
#   - export NPM_CONFIG_PREFIX=/home/node/.npm-global
#   - export PATH=$PATH:/home/node/.npm-global/bin
#   - npm install electron-packager -g
#   - npm install electron-installer-dmg -g

buildDMG:
  script:
   - npm install
   - electron-builder build --mac
#   artifacts:
#     paths:
#       - dmg/CTVisualizer.dmg

