# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  
before_script:
  - pwd
  - whoami
  - npm install electron-packager -g

buildTar:
  script:
   - npm install
   - electron-packager . CTVisualizer --platform=darwin --arch=x64 --out=./packaged-app --app-category-type=public.app-category.developer-tools --icon=/builds/ctvisualizer/front-end/res/logo4.icns
   - cd ./packaged-app/CTVisualizer-darwin-x64
   - tar -zcvf CTVisualizer-darwin-x64.tar.gz *
   - cd ../..
   - cp ./packaged-app/CTVisualizer-darwin-x64/CTVisualizer-darwin-x64.tar.gz .
  artifacts:
    paths:
      - CTVisualizer-darwin-x64.tar.gz